"use client";

/* eslint-disable react-hooks/exhaustive-deps */

import { FormEvent, useEffect, useState } from "react";
import { FormSkeleton } from "@/components/Loaders";
import { useParams, useRouter } from "next/navigation";

type Form = { fullName: string; cnic: string; gender: string; className: string; section: string; rollNumber: string; fatherName: string; fatherPhone: string; homeAddress: string };

export default function TeacherEditStudentPage() {
  const router = useRouter(); const params = useParams<{ id: string }>();
  const [classes, setClasses] = useState<string[]>([]); const [form, setForm] = useState<Form>({ fullName: "", cnic: "", gender: "", className: "", section: "", rollNumber: "", fatherName: "", fatherPhone: "", homeAddress: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([fetch(`/api/students/${params.id}`).then((response) => response.json()), fetch("/api/teachers/me/classes").then((response) => response.json())]).then(([studentResult, classResult]) => { if (studentResult.error) setError(studentResult.error); else setForm((current) => ({ ...current, ...studentResult.student, className: String(studentResult.student.class ?? ""), section: String(studentResult.student.section ?? "").toUpperCase() })); if (classResult.error) setError(classResult.error); else setClasses(classResult.assignedClasses); }).catch(() => setError("Unable to connect to the server")).finally(() => setLoading(false)); }, []);
  function update(key: keyof Form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function chooseClass(value: string) { const parts = value.split("-"); setForm((current) => ({ ...current, className: parts[0] ?? "", section: parts.slice(1).join("-") })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch(`/api/students/${params.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Unable to update student"); else { router.push("/teacher/students"); router.refresh(); } setSaving(false); }
  return <main className="min-h-screen bg-slate-100 px-6 py-8 text-slate-900 sm:px-10"><div className="mx-auto max-w-3xl"><a href="/teacher/students" className="text-sm font-medium text-blue-600">← My students</a><h1 className="mt-6 text-3xl font-bold">Edit student</h1><p className="mt-2 text-slate-500">You can edit students only within your Admin-assigned classes.</p>{loading ? <FormSkeleton fields={4} /> : <form onSubmit={submit} className="mt-8 rounded-2xl bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Full name<input required value={form.fullName} onChange={(event) => update("fullName", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-medium">CNIC<input required value={form.cnic} onChange={(event) => update("cnic", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-medium">Gender<select required value={form.gender} onChange={(event) => update("gender", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"><option value="">Select gender</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label><label className="text-sm font-medium sm:col-span-2">Class and section<select required value={`${form.className}-${form.section}`} onChange={(event) => chooseClass(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3">{classes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium">Roll number<input required value={form.rollNumber} onChange={(event) => update("rollNumber", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-medium">Father name<input value={form.fatherName} onChange={(event) => update("fatherName", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-medium">Parent phone<input value={form.fatherPhone} onChange={(event) => update("fatherPhone", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-medium sm:col-span-2">Home address<textarea value={form.homeAddress} onChange={(event) => update("homeAddress", event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 px-4 py-3" /></label></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving || !classes.length} className="mt-7 w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{saving ? "Saving..." : "Save student"}</button></form>}</div></main>;
}
