"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function NewClassPage() {
  const router = useRouter();
  const [form, setForm] = useState({ className: "", sectionName: "", academicYear: "2026-2027", capacity: "50" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/classes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, capacity: Number(form.capacity) }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to create class"); return; } router.push("/dashboard/classes"); router.refresh(); } catch { setError("Unable to connect to the server"); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-slate-100 px-6 py-8 text-slate-900 sm:px-10"><div className="mx-auto max-w-2xl"><a href="/dashboard/classes" className="text-sm font-medium text-blue-600">← Classes & sections</a><h1 className="mt-6 text-3xl font-bold tracking-tight">Create class section</h1><p className="mt-2 text-slate-500">Keep classes and sections structured for reliable filtering.</p><form onSubmit={submit} className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Class<input required value={form.className} onChange={(e) => update("className", e.target.value)} placeholder="7" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" /></label><label className="text-sm font-medium">Section<input required value={form.sectionName} onChange={(e) => update("sectionName", e.target.value)} placeholder="A" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 uppercase outline-none focus:border-blue-500" /></label><label className="text-sm font-medium">Academic year<input required value={form.academicYear} onChange={(e) => update("academicYear", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" /></label><label className="text-sm font-medium">Capacity<input required min="1" type="number" value={form.capacity} onChange={(e) => update("capacity", e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" /></label></div>{error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-3"><a href="/dashboard/classes" className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold text-slate-600">Cancel</a><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Saving..." : "Create class"}</button></div></form></div></main>;
}
